//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/21 - 06:55:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace drs_backend_phase1.Models.DTOs
{
    public partial class EventLogDTO
    {
        public int id { get; set; }

        public string typeKey { get; set; }

        public int? configId { get; set; }

        public int? userId { get; set; }

        public string userName { get; set; }

        public DateTime createDate { get; set; }

        public string serverName { get; set; }

        public string properties { get; set; }

        public EventLogConfigDTO EventLogConfig { get; set; }

        public EventLogTypeDTO EventLogType { get; set; }

        public EventLogDTO()
        {
        }

        public EventLogDTO(int id, string typeKey, int? configId, int? userId, string userName, DateTime createDate, string serverName, string properties, EventLogConfigDTO eventLogConfig, EventLogTypeDTO eventLogType)
        {
			this.id = id;
			this.typeKey = typeKey;
			this.configId = configId;
			this.userId = userId;
			this.userName = userName;
			this.createDate = createDate;
			this.serverName = serverName;
			this.properties = properties;
			this.EventLogConfig = eventLogConfig;
			this.EventLogType = eventLogType;
        }
    }
}