//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/22 - 20:54:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace drs_backend_phase1.Models.DTOs
{
    public partial class AgencyDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileProfessionalDTO> ProfileProfessionals { get; set; }
    }

    public partial class BankDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileFinanceDTO> ProfileFinances { get; set; }
    }

    public partial class BaseDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool? isDeleted { get; set; }

        public int teamId { get; set; }

        //public List<ProfileProfessionalDTO> ProfileProfessionals { get; set; }

        //public TeamDTO Team { get; set; }
    }

    public partial class CCGDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileProfessionalDTO> ProfileProfessionals { get; set; }
    }

    public partial class DocumentTypeDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileDocumentDTO> ProfileDocuments { get; set; }
    }

    public partial class EmailDTO
    {
        public string to { get; set; }

        public string from { get; set; }

        public string subject { get; set; }

        public string text { get; set; }

        public int id { get; set; }

        public DateTime? dateCreated { get; set; }

        public DateTime? dateModified { get; set; }

        public bool? isDeleted { get; set; }
    }

    public partial class IndemnityProviderDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileProfessionalDTO> ProfileProfessionals { get; set; }
    }

    public partial class JobTypeDTO
    {
        public string name { get; set; }

        public bool? isClinical { get; set; }

        public bool? isGmcRequired { get; set; }

        public bool? isNmcRequired { get; set; }

        public bool? isHcpcRequired { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool? isDeleted { get; set; }

        //public List<ProfileProfessionalDTO> ProfileProfessionals { get; set; }
    }

    public partial class PaymentCategoryDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfilePaymentCategoryDTO> ProfilePaymentCategories { get; set; }
    }

    public partial class ProfileDTO
    {
        public string firstName { get; set; }

        public string middleNames { get; set; }

        public string lastName { get; set; }

        public DateTime dateOfBirth { get; set; }

        public string address1 { get; set; }

        public string address2 { get; set; }

        public string address3 { get; set; }

        public string address4 { get; set; }

        public string address5 { get; set; }

        public string postcode { get; set; }

        public string homePhone { get; set; }

        public string mobilePhone { get; set; }

        public string homeEmail { get; set; }

        public string nhsEmail { get; set; }

        public bool smsEnabled { get; set; }

        public bool isInactive { get; set; }

        public bool isComplete { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        public int? profileProfessionalId { get; set; }

        public int? profileFinanceId { get; set; }

        public string adEmailAddress { get; set; }

        public byte? roleID { get; set; }

        public List<SpecialNoteDTO> SpecialNotes { get; set; }

        public ProfileProfessionalDTO ProfileProfessional { get; set; }

        public List<ProfileDocumentDTO> ProfileDocuments { get; set; }

        public ProfileFinanceDTO ProfileFinance { get; set; }

        public SecurityRoleDTO SecurityRole { get; set; }
    }

    public partial class ProfileDocumentDTO
    {
        public int? documentTypeId { get; set; }

        public string originalFileName { get; set; }

        public string multerFileName { get; set; }

        public string mimeType { get; set; }

        public DateTime? dateObtained { get; set; }

        public DateTime? dateExpires { get; set; }

        public int? profileId { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        public DocumentTypeDTO DocumentType { get; set; }

        //public ProfileDTO Profile { get; set; }
    }

    public partial class ProfileFinanceDTO
    {
        public string payrollNumber { get; set; }

        public bool isIc24Staff { get; set; }

        public string nationalInsuranceNumber { get; set; }

        public int? bankId { get; set; }

        public string bankAccountNumber { get; set; }

        public string bankSortCode { get; set; }

        public string buildingSocietyRollNumber { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        public BankDTO Bank { get; set; }

        //public List<ProfileDTO> Profiles { get; set; }
    }

    public partial class ProfilePaymentCategoryDTO
    {
        public int? paymentCategoryId { get; set; }

        public int? profileProfessionalId { get; set; }

        public bool isDefault { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        public PaymentCategoryDTO PaymentCategory { get; set; }

        //public ProfileProfessionalDTO ProfileProfessional { get; set; }
    }

    public partial class ProfileProfessionalDTO
    {
        public int? teamId { get; set; }

        public int? jobTypeId { get; set; }

        public string gmcNumber { get; set; }

        public string nmcNumber { get; set; }

        public string hcpcNumber { get; set; }

        public DateTime? registrationExpiryDate { get; set; }

        public int? subTypeId { get; set; }

        public int? registrarLevelId { get; set; }

        public string registrarTrainer { get; set; }

        public bool isRegistrarGreen { get; set; }

        public int? agencyId { get; set; }

        public int? registeredSurgeryId { get; set; }

        public int? ccgId { get; set; }

        public int? indemnityProviderId { get; set; }

        public string performersList { get; set; }

        public bool performersListChecked { get; set; }

        public DateTime? performersListCheckedDate { get; set; }

        public string performersListCheckedBy { get; set; }

        public string indemnityNumber { get; set; }

        public DateTime? indemnityExpiryDate { get; set; }

        public bool isPremium { get; set; }

        public bool isTrainer { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        public int? baseId { get; set; }

        public AgencyDTO Agency { get; set; }

        public BaseDTO Base_ { get; set; }

        public CCGDTO CCG { get; set; }

        public IndemnityProviderDTO IndemnityProvider { get; set; }

        public JobTypeDTO JobType { get; set; }

        //public List<ProfileDTO> Profiles { get; set; }

        public List<ProfilePaymentCategoryDTO> ProfilePaymentCategories { get; set; }

        public SubTypeDTO SubType { get; set; }

        public List<ProfileShiftTypeDTO> ProfileShiftTypes { get; set; }

        public RegisteredSurgeryDTO RegisteredSurgery { get; set; }

        public RegistrarLevelDTO RegistrarLevel { get; set; }
    }

    public partial class ProfileShiftTypeDTO
    {
        public int? shiftTypeId { get; set; }

        public int? profileProfessionalId { get; set; }

        public bool? isUnderReview { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public ProfileProfessionalDTO ProfileProfessional { get; set; }

        public ShiftTypeDTO ShiftType { get; set; }
    }

    public partial class RegisteredSurgeryDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileProfessionalDTO> ProfileProfessionals { get; set; }
    }

    public partial class RegistrarLevelDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileProfessionalDTO> ProfileProfessionals { get; set; }
    }

    public partial class SecurityRoleDTO
    {
        public byte roleId { get; set; }

        public string roleName { get; set; }

        public DateTime validFrom { get; set; }

        public DateTime validTo { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public int? createdProfileID { get; set; }

        public int? modifiedProfileID { get; set; }

        public bool? isDeleted { get; set; }

        //public List<ProfileDTO> Profiles { get; set; }
    }

    public partial class ShiftTypeDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileShiftTypeDTO> ProfileShiftTypes { get; set; }
    }

    public partial class SpecialNoteDTO
    {
        public string userName { get; set; }

        public string noteText { get; set; }

        public int profileId { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool? isDeleted { get; set; }

        //public ProfileDTO Profile { get; set; }
    }

    public partial class SubTypeDTO
    {
        public string name { get; set; }

        public bool isAgency { get; set; }

        public bool isRegistrar { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        //public List<ProfileProfessionalDTO> ProfileProfessionals { get; set; }
    }

    public partial class TeamDTO
    {
        public int id { get; set; }

        public string name { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

        public List<BaseDTO> Bases { get; set; }
    }
}