//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/21 - 07:00:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace drs_backend_phase1.Models.DTOs
{
    public partial class ProfileDocumentDTO
    {
        public int? documentTypeId { get; set; }

        public string originalFileName { get; set; }

        public string multerFileName { get; set; }

        public string mimeType { get; set; }

        //public DateTime? dateObtained { get; set; }

        //public DateTime? dateExpires { get; set; }

        //public int? profileId { get; set; }

        public int id { get; set; }

        //public DateTime? dateCreated { get; set; }

        //public DateTime? dateModified { get; set; }

        public bool isDeleted { get; set; }

    }
}