//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/21 - 07:00:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace drs_backend_phase1.Models.DTOs
{
    public partial class SecurityRightDTO
    {
        public byte rightID { get; set; }

        public string rightName { get; set; }

        public DateTime validFrom { get; set; }

        public DateTime validTo { get; set; }

        public DateTime? dateCreated { get; set; }
    }
}