//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/21 - 07:00:53
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace drs_backend_phase1.Models.DTOs
{
    public partial class SecurityGroupDTO
    {
        public byte groupId { get; set; }

        public string groupName { get; set; }

        //public DateTime validFrom { get; set; }

        //public DateTime validTo { get; set; }

        public List<SecurityPermissionDTO> SecurityPermissions { get; set; }

        public SecurityGroupDTO()
        {
        }

    }
}