//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drs_backend_phase1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilePaymentCategory
    {
        public Nullable<int> paymentCategoryId { get; set; }
        public Nullable<int> profileProfessionalId { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual ProfileProfessional ProfileProfessional { get; set; }
    }
}
