//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drs_backend_phase1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileProfessional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileProfessional()
        {
            this.Profiles = new HashSet<Profile>();
            this.ProfilePaymentCategories = new HashSet<ProfilePaymentCategory>();
            this.ProfileShiftTypes = new HashSet<ProfileShiftType>();
        }
    
        public Nullable<int> teamId { get; set; }
        public Nullable<int> jobTypeId { get; set; }
        public string gmcNumber { get; set; }
        public string nmcNumber { get; set; }
        public string hcpcNumber { get; set; }
        public Nullable<System.DateTime> registrationExpiryDate { get; set; }
        public Nullable<int> subTypeId { get; set; }
        public Nullable<int> registrarLevelId { get; set; }
        public string registrarTrainer { get; set; }
        public Nullable<bool> isRegistrarGreen { get; set; }
        public Nullable<int> agencyId { get; set; }
        public Nullable<int> registeredSurgeryId { get; set; }
        public Nullable<int> ccgId { get; set; }
        public Nullable<int> indemnityProviderId { get; set; }
        public string performersList { get; set; }
        public Nullable<bool> performersListChecked { get; set; }
        public Nullable<System.DateTime> performersListCheckedDate { get; set; }
        public string performersListCheckedBy { get; set; }
        public string indemnityNumber { get; set; }
        public Nullable<System.DateTime> indemnityExpiryDate { get; set; }
        public Nullable<bool> isPremium { get; set; }
        public Nullable<bool> isTrainer { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> baseId { get; set; }
    
        public virtual JobType JobType { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Lookup Lookup1 { get; set; }
        public virtual Lookup Lookup2 { get; set; }
        public virtual Lookup Lookup3 { get; set; }
        public virtual Lookup Lookup4 { get; set; }
        public virtual Lookup Lookup5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile> Profiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilePaymentCategory> ProfilePaymentCategories { get; set; }
        public virtual SubType SubType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileShiftType> ProfileShiftTypes { get; set; }
        public virtual Agency Agency { get; set; }
        public virtual Base Base { get; set; }
        public virtual CCG CCG { get; set; }
        public virtual IndemnityProvider IndemnityProvider { get; set; }
        public virtual RegisteredSurgery RegisteredSurgery { get; set; }
        public virtual RegistrarLevel RegistrarLevel { get; set; }
        public virtual Team Team { get; set; }
    }
}
