//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drs_backend_phase1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityPermission
    {
        public int PermissionID { get; set; }
        public byte GroupID { get; set; }
        public byte RoleID { get; set; }
        public byte RightID { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> CreatedProfileID { get; set; }
        public Nullable<int> ModifiedProfileID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual SecurityGroup SecurityGroup { get; set; }
        public virtual SecurityRight SecurityRight { get; set; }
        public virtual SecurityRole SecurityRole { get; set; }
    }
}
