//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drs_backend_phase1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialNote
    {
        public string userName { get; set; }
        public string noteText { get; set; }
        public int profileId { get; set; }
        public int id { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateModified { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
